// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/md5.proto

package grpcclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Md5Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StringToHash string `protobuf:"bytes,1,opt,name=stringToHash,proto3" json:"stringToHash,omitempty"`
}

func (x *Md5Request) Reset() {
	*x = Md5Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_md5_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Md5Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Md5Request) ProtoMessage() {}

func (x *Md5Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_md5_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Md5Request.ProtoReflect.Descriptor instead.
func (*Md5Request) Descriptor() ([]byte, []int) {
	return file_proto_md5_proto_rawDescGZIP(), []int{0}
}

func (x *Md5Request) GetStringToHash() string {
	if x != nil {
		return x.StringToHash
	}
	return ""
}

type Md5Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashCode string `protobuf:"bytes,1,opt,name=hashCode,proto3" json:"hashCode,omitempty"`
}

func (x *Md5Reply) Reset() {
	*x = Md5Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_md5_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Md5Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Md5Reply) ProtoMessage() {}

func (x *Md5Reply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_md5_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Md5Reply.ProtoReflect.Descriptor instead.
func (*Md5Reply) Descriptor() ([]byte, []int) {
	return file_proto_md5_proto_rawDescGZIP(), []int{1}
}

func (x *Md5Reply) GetHashCode() string {
	if x != nil {
		return x.HashCode
	}
	return ""
}

var File_proto_md5_proto protoreflect.FileDescriptor

var file_proto_md5_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x64, 0x35, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x30, 0x0a, 0x0a, 0x4d, 0x64, 0x35, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x48,
	0x61, 0x73, 0x68, 0x22, 0x26, 0x0a, 0x08, 0x4d, 0x64, 0x35, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x68, 0x61, 0x73, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x4f, 0x0a, 0x07, 0x4d,
	0x64, 0x35, 0x47, 0x72, 0x70, 0x63, 0x12, 0x44, 0x0a, 0x0a, 0x4d, 0x64, 0x35, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x67, 0x72, 0x70, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x64, 0x35, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4d, 0x64, 0x35, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x46, 0x0a, 0x0e,
	0x6e, 0x65, 0x74, 0x2e, 0x6c, 0x69, 0x74, 0x74, 0x6c, 0x65, 0x6c, 0x69, 0x74, 0x65, 0x42, 0x0c,
	0x4d, 0x64, 0x35, 0x67, 0x52, 0x70, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x24,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x75, 0x69, 0x6c, 0x64,
	0x65, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x6e, 0x37, 0x30, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_md5_proto_rawDescOnce sync.Once
	file_proto_md5_proto_rawDescData = file_proto_md5_proto_rawDesc
)

func file_proto_md5_proto_rawDescGZIP() []byte {
	file_proto_md5_proto_rawDescOnce.Do(func() {
		file_proto_md5_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_md5_proto_rawDescData)
	})
	return file_proto_md5_proto_rawDescData
}

var file_proto_md5_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_md5_proto_goTypes = []interface{}{
	(*Md5Request)(nil), // 0: smartgrpcproto.Md5Request
	(*Md5Reply)(nil),   // 1: smartgrpcproto.Md5Reply
}
var file_proto_md5_proto_depIdxs = []int32{
	0, // 0: smartgrpcproto.Md5Grpc.Md5Service:input_type -> smartgrpcproto.Md5Request
	1, // 1: smartgrpcproto.Md5Grpc.Md5Service:output_type -> smartgrpcproto.Md5Reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_md5_proto_init() }
func file_proto_md5_proto_init() {
	if File_proto_md5_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_md5_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Md5Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_md5_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Md5Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_md5_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_md5_proto_goTypes,
		DependencyIndexes: file_proto_md5_proto_depIdxs,
		MessageInfos:      file_proto_md5_proto_msgTypes,
	}.Build()
	File_proto_md5_proto = out.File
	file_proto_md5_proto_rawDesc = nil
	file_proto_md5_proto_goTypes = nil
	file_proto_md5_proto_depIdxs = nil
}
